version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      minimum-age-days: 5

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      minimum-age-days: 5

  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    cooldown:
      minimum-age-days: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      minimum-age-days: 5
